base
novikovanat/team-icecream-12 pull request #5
Opened 2020-12-16 21:49 UTC by Ahvizra

2020-12-16 22:29 UTC, MeatyRenegade approved these changes

2020-12-17 07:38 UTC, novikovanat requested changes
* line-height указывается множителем 
* лучше оставить ширину по содержимому и добавить паддинги
* при ховере цвет шрифта не менятеся

2020-12-17 09:38 UTC, iborovikov approved these changes

2020-12-17 18:57 UTC, iborovikov approved these changes

2020-12-17 18:57 UTC, MeatyRenegade approved these changes

2020-12-17 18:58 UTC, novikovanat approved these changes

2020-12-17 19:01 UTC, closed without merging